cmd/init/testnet.go
=> minimum gas price bug

x/budget/keeper.go
=> Remove unnecessary conversion

.circleci/config.yml, .goreleaser.yml
Added a releasing job to CI when versioning with `git tag`:
- Details are: https://circleci.com/gh/terra-project/core/339
=> Add release to CI

README.md
=> Update README.md chain-id

x/budget/msg.go, x/market/msg.go, x/oracle/msg.go
change msg get sign bytes to use msgCdc
=> change msg get sign bytes to use msgCdc

app/genesis.go, x/bench/bench_test_common.go, x/bench/treasury_bench_test.go, x/market/handler.go
=> fixed merge conflicts

app/app.go, app/genesis.go, go.mod, go.sum, types/codec.go, types/graded_account.go, types/graded_account_test.go
fix graded account amino struct
=> fix graded account amino struct

client/lcd/swagger-ui/swagger.yaml
Swagger updated to fit new REST style.
=> Swagger update

docs/guide/installation.md
=> Make sure user has golang bin PATH set

.circleci/config.yml
circleci golang version update to v1.12.3
=> circleci golang version update

README.md
- reflected mainnet launch status
- edited documentation links
- provided credit to ecosystem tool creators
=> changed main readme

app/app.go, x/budget/client/rest/query.go, x/market/client/cli/cli_test.go, x/market/client/cli/query.go, x/market/client/module_client.go, x/market/client/rest/query.go, x/market/client/rest/rest.go, x/market/constants.go, x/market/querier.go, x/oracle/client/cli/tx.go, x/oracle/client/rest/tx.go, x/oracle/querier.go
Implement market querier to get real swap amount of swap operation
=> add market querier & fix oracle cli tx prevote/vote

client/lcd/swagger-ui/swagger.yaml, x/market/client/module_client.go, x/market/params.go, x/market/querier.go
swagger update
change default params of market
add market param querier path
=> update swagger & market querier

client/lcd/swagger-ui/swagger.yaml, x/budget/client/cli/query.go, x/budget/querier.go, x/budget/querier_test.go, x/mint/keeper.go, x/mint/keeper_test.go, x/oracle/client/cli/query.go, x/oracle/client/rest/query.go, x/oracle/denom.go, x/oracle/keeper.go, x/oracle/querier.go, x/oracle/querier_test.go, x/slashing/client/cli/query.go, x/staking/client/cli/query.go, x/treasury/client/cli/query.go, x/treasury/client/rest/query.go, x/treasury/querier.go, x/treasury/querier_test.go
Array and string responses are changed to JSON format (underscore formatting)
```
(GET) /budget/programs/{programId}/votes
(GET) /budget/programs/{programId}/votes/{voter}
(GET) /budget/programs/actives
(GET) /budget/programs/candidates
(GET) /oracle/denoms/{denom}/votes
(GET) /oracle/denoms/{denom}/votes/{voter}
(GET) /oracle/denoms/{denom}/prevotes
(GET) /oracle/denoms/{denom}/prevotes/{voter}
(GET) /oracle/denoms/{denom}/price
(GET) /oracle/denoms/actives
(GET) /treasury/tax-rate
(GET) /treasury/tax-rate/{epoch}
(GET) /treasury/tax-cap/{denom}
(GET) /treasury/reward-weight
(GET) /treasury/reward-weight/{denom}
(GET) /treasury/issuance/{denom}
(GET) /treasury/issuance/{denom}/{day}
(GET) /treasury/tax-proceeds
(GET) /treasury/tax-proceeds/{epoch}
(GET) …
```
=> align querier response to json

app/app.go, update/end_blocker.go
Add chain id check to update endblocker only for columbus-2
** Report of required housekeeping ** 
======
** (FOR ADMIN) Before merging **
=> Add chain id check to update endblocker only for columbus-2

docs/SUMMARY.md
I missed to add page in summary.
----
=> Added production link to Summary

x/treasury/client/cli/tx.go
Fix description for `$terracli tx gov submit-proposal reward-weight-update ...`
----
=> Fix wrong terracli description

x/market/client/rest/query.go, x/oracle/client/rest/query.go, x/treasury/client/rest/query.go
* Fix all query response to be bonded with height
----
=> [Bugfix] Fix all query response to be bonded with height

client/lcd/swagger-ui/swagger.yaml, x/oracle/client/rest/query.go, x/oracle/internal/keeper/keeper.go, x/oracle/internal/keeper/keeper_test.go, x/oracle/internal/keeper/querier.go, x/oracle/internal/keeper/querier_test.go, x/oracle/internal/types/querier.go
* Append a single end point to query all prevotes of a validator 
* Append a single end point to query all votes of a validator
* Append a single end point to query all active luna prices
#192 
----
=> [Feature] oracle endpoints improvement

app/app.go, app/app_test.go
Remove oracle account address from send blacklist
----
=> [Bugfix] Remove oracle account address from send blacklist

go.mod, go.sum
* Bump SDK version to v0.37.4
----
=> Bump SDK version to v0.37.4

x/oracle/abci_test.go, x/oracle/tally.go
* Apply oracle reward spread with multiplication operation
close #280 
----
=> [Bug] fix to apply reward spread by multiplication

x/oracle/alias.go, x/oracle/internal/types/errors.go, x/oracle/internal/types/msgs.go, x/oracle/internal/types/msgs_test.go
* Allow non-positive exchange-rate vote
----
=> [Bugfix] Allow non-positive exchange-rate vote

x/market/handler.go, x/oracle/handler.go
* Create new event manager in `NewHandler`
close #289 
----
=> [Bug] Create new event manager per tx

x/oracle/client/cli/query.go, x/oracle/genesis.go, x/oracle/handler.go, x/oracle/internal/keeper/keeper.go, x/oracle/internal/keeper/keeper_test.go, x/oracle/internal/keeper/querier.go, x/oracle/internal/keeper/querier_test.go, x/oracle/internal/types/msgs.go, x/oracle/internal/types/msgs_test.go, x/oracle/internal/types/params.go
* Change oracle MsgDelegateFeedConsent.Deleagtee to MsgDelegateFeedConsent.Deleagte
----
=> [Feature] oracle MsgDelegateFeedConsent.Deleagtee to Delegate

.gitignore, .goreleaser.yml
* update go-releaser for the columbus-3 build
----
=> [Feature] Update go-releaser

x/oracle/internal/types/errors.go, x/treasury/internal/types/params.go
* Update treasury['params']['reward_policy']['rate_max'] to 50%
----
=> [Param] Update default reward policy param

x/oracle/client/rest/query.go
=> [Bugfix] Fix oracle endpoint to accept voter variable

contrib/updates/columbus-2-to-columbus-3.py
Genesis update script from columbus-2 to columbus-3
It migrates modules and creates module accounts.
----
=> genesis update script for columbus-3 (wip)

.circleci/config.yml
* Change circleci to execute gorelease for every tag
----
=> [Feature] Auto gorelease execution

x/auth/client/utils/feeutils.go, x/market/abci_test.go
* Build simulation tx body with empty signatures as many as necessary for the msgs
close #302 
----
=> [Bugfix] Fix fee estimation for the tx which requires multiple signers

go.mod, go.sum
* Bump SDK version to v0.37.6
----
=> Bump SDK version to v0.37.6

go.sum, x/oracle/internal/keeper/reward.go
* revert to distribute zero oracle reward
----
=> Revert to distribute zero oracle reward

x/slashing/internal/types/codec.go
* Change slashing unjail msg codec name
close #326 
----
=> [Bug] slashing codec

app/export.go
Before exporting for zero height, fill address to signing_info.
close #328 
----
=> [Bugfix] Fill address to signing info

client/lcd/swagger-ui/swagger.yaml
Fix '/distribution/parameters' url typo in swagger.yaml
----
=> Update broken url link in swagger

client/lcd/swagger-ui/swagger.yaml, x/auth/ante/tax.go, x/auth/client/utils/feeutils.go, x/market/client/cli/tx.go, x/market/client/rest/tx.go, x/market/exported/alias.go, x/treasury/exported/alias.go
* Add tax calculation function to market cli & rest interfaces
* Convert swap request to generate MsgSwap when the receiver is empty
----
=> [Feature] market client interface tax calculation

client/lcd/swagger-ui/swagger.yaml, x/wasm/client/cli/query.go, x/wasm/client/cli/tx.go, x/wasm/client/rest/query.go, x/wasm/client/rest/tx.go, x/wasm/internal/keeper/querier.go, x/wasm/internal/keeper/querier_test.go, x/wasm/internal/types/querier.go
* Add WASM params querier client interface 
* Align rest interface msgs
----
=> [Feature] WASM add params querier interface & align client interface

x/market/handler.go, x/market/handler_test.go, x/wasm/simulation/operations.go
=> [Bugfix] market swap pool adjustment

.circleci/config.yml
CosmWasm is using its own shared library `libgo_cosmwasm.so`, so providing prebuilt binary is not that meaningful.
----
=> [Feature] remove goreleaser ci

x/distribution/internal/types/codec.go
* add missing distribution codec for MsgFundCommunityPool
----
=> [Feature] Align code style

.circleci/config.yml, Dockerfile, Makefile, docker-compose.yml, networks/local/Makefile, networks/local/core/Dockerfile
Reduce image size
Update CI to push to the terramoney docker hub org
=> Update docker image and change docker hub repo

x/msgauth/simulation/operations.go
* Allow insufficient fee error for msgauth simulation
----
=> [Bugfix] Allow insufficient fee error for msgauth simulation

client/lcd/root.go, client/lcd/swagger-ui/swagger.yaml, cmd/terracli/main.go, x/auth/client/rest/query.go, x/auth/client/rest/rest.go, x/treasury/client/cli/query.go, x/treasury/client/rest/query.go, x/treasury/internal/keeper/querier.go, x/treasury/internal/keeper/querier_test.go, x/treasury/internal/types/querier.go
As discussed #368 , I added couple of features
* Add public flag at staring rest-server and enforce to use `tx.height` option when public flag is on
* treasury indicator querier to enable tracking on `tax-rate` update
close #368 
----
=> [Feature] live tracing branch features

x/oracle/abci.go, x/oracle/internal/keeper/keeper.go, x/oracle/internal/types/ballot.go, x/oracle/internal/types/ballot_test.go, x/oracle/tally.go
Align oracle module codes
----
=> [Feature] Clean oracle module

app/app.go, app/sim_test.go, cli_test/cli_test.go, cli_test/test_helpers.go, x/mint/cosmos_alias.go, x/mint/module.go
* Activate mint module from cosmos-sdk for future use
We will set 0 inflation params at Columbus-4. Later community can increase inflation params via gov proposer.
----
=> [Feature] Mint Module

.github/pull_request_template.md, client/lcd/swagger-ui/swagger.yaml
* add mint module endpoints
* modify PR template to include swagger update
----
=> [Feature] swagger update for mint module

go.mod, go.sum
* Bump CosmWasm to v0.10.1
- [Fix iteration bug](https://github.com/CosmWasm/cosmwasm/blob/master/CHANGELOG.md#0101-2020-08-25)
----
=> [Feature] Bump cosmwasm to v0.10.1

go.mod
* Change CosmWasm version to v0.10.1 instead of v0.0.0
----
=> change replace versioning

Dockerfile
Related to https://github.com/terra-project/core/issues/393, https://github.com/terra-project/core/pull/395 and https://github.com/terra-project/images/issues/1
=> Update swagger on docker image build

x/market/internal/types/msgs.go, x/msgauth/client/rest/rest.go, x/msgauth/client/rest/tx.go, x/msgauth/internal/keeper/keeper.go, x/wasm/client/utils/utils.go, x/wasm/internal/keeper/api.go
Apply recommendations from Certik
close #400 
----
=> [Audit] apply Certik audit report

x/market/internal/types/errors.go, x/msgauth/internal/types/errors.go, x/oracle/internal/types/errors.go, x/treasury/alias.go, x/treasury/internal/types/errors.go, x/wasm/internal/types/errors.go
Reverts terra-project/core#417
This change causes result hash mismatch at height 1078 which has an error from MsgSwap message https://finder.terra.money/columbus-4/tx/A9D1B105BEC86B4043162635B68DA4F9BE4FE240D916E4EB8205C1F6DDDB0E89
=> Revert "[Bugfix] Make all error code bigger than 1"

x/market/client/cli/query.go, x/wasm/internal/keeper/contract.go, x/wasm/internal/types/errors.go
=> [Bugfix] Register wasm query failed error to sdkerrors

x/treasury/internal/keeper/querier.go
=> [Bugfix] Fix treasury indicators querier

client/lcd/swagger-ui/swagger.yaml, x/treasury/client/cli/query.go, x/treasury/client/rest/query.go, x/treasury/internal/keeper/querier.go, x/treasury/internal/keeper/querier_test.go, x/treasury/internal/types/querier.go
=> Implement tax caps querier for all whitelisted denoms

x/treasury/client/cli/utils.go, x/treasury/internal/types/proposal.go
=> [Bugfix] RewardWeightUpdateProposal CLI parse error

go.mod, go.sum, x/auth/ante/tax.go
close #478 
Also we have more strict gas usage for oracle messages to prevent huge gas consumption.
----
=> [Feature] mempool logic update to give oracle message priority

contrib/images/terrad-env/Dockerfile
Fixes broken Github Action liveness-test workflow using localnet-start.
----
=> fix(terrad-env): Dockerfile VOLUME directive doesn't work on Azure

custom/auth/legacy/v040/migrate.go
=> [Bugfix] treasury module burn permission

README.md
The previous one got invalidated.
----
=> Update Discord Invite link

app/app.go, custom/authz/client/cli/tx.go, custom/authz/module.go, custom/authz/types/codec.go
=> [Feature] amino support to authz module with tax computing custom cli

custom/authz/types/codec.go
Add custom amino support for `StakeAuthorization`. 
```
cdc.RegisterConcrete(&stakingtypes.StakeAuthorization{}, "msgauth/StakeAuthorization", nil)
```
----
=> [Feature] Add amino support for StakeAuthorization

CHANGELOG.md, docs/core/proto-docs.md, go.mod, go.sum, third_party/proto/google/protobuf/any.proto, third_party/proto/ibc/core/client/v1/client.proto, third_party/proto/ibc/core/connection/v1/connection.proto, third_party/proto/ibc/core/connection/v1/genesis.proto, third_party/proto/ibc/lightclients/solomachine/v2/solomachine.proto
close #524 
* Bump CosmosSDK to v0.43
* Bump IBC to v1.0.0
* Replace keyring to cosmos keyring to fix kwallet problems [refer](https://github.com/cosmos/cosmos-sdk/pull/9563)
----
=> bump sdk version to 0.43 and ibc-go version to 1.0.0

app/app.go
removed unused upgrade code for `bombay-11`
----
=> remove unused upgrade code for bombay-11

CHANGELOG.md
- Fix broken release tag URLs in CHANGELOG.md
- Clean up trailing whitespace
=> Update release tag URLs in CHANGELOG.md

scripts/statesync.bash
=> State sync script

README.md
Adds a quickstart to readme.md andpulls the 
----
=> Quickstart in readme using ipfs instead of aws

x/treasury/module.go
Noticed these comments were incorrectly mentioning the oracle module. 
----
=> docs: Update treasury module comments.

go.mod, go.sum
Bump SDK to v0.44.5 with iavl bug fix
----
=> bump sdk to v0.44.5

go.mod, go.sum
Bump IBC to latest [v1.1.5](https://github.com/cosmos/ibc-go/releases/tag/v1.1.5)
----
=> update ibc to latest

Dockerfile, go.mod, go.sum
=> bump wasmvm to v0.16.3

README.md
Change to README:
RPM is dropped and Linux distributions are recommended.
More info: https://github.com/terra-money/docs/pull/207
----
=> Update readme requirements

go.mod, go.sum
=> This paves the way for the use of rocksdb by default.

x/market/spec/01_concepts.md
=> docs: fix typo(LunaPice -> LunaPrice)

CHANGELOG.md, x/wasm/keeper/reflect_test.go, x/wasm/keeper/wasm_interface_stargate.go
=> apply v0.5.17

x/wasm/types/connector.go
=> [Bugfix] check nil before dereferencing

.github/workflows/lint.yml
=> update golangci-lint version

x/wasm/keeper/keeper.go
Fix typo in wasm module (original: https://github.com/terra-money/core/pull/696)
----
=> Fix typo in wasm error log

Dockerfile
Add more build flags as described in https://github.com/CosmWasm/wasmvm/wiki/Linking-wasmvm_muslc
----
=> add static build flags

CHANGELOG.md
update changelog for v0.5.18 release
----
=> Update CHANGELOG for v0.5.18

x/oracle/abci.go, x/oracle/keeper/reward.go, x/oracle/tally.go, x/oracle/types/ballot.go, x/oracle/types/ballot_test.go
remove unused softfork codes
----
=> remove unused oracle softfork codes

x/market/keeper/msg_server.go, x/market/keeper/msg_server_test.go
=> [Feature] split swap spread between oracle voting rewards and block validation rewards

x/oracle/keeper/reward.go
1. Updated notes to reflect the fact that oracle rewards come from spread fees, not from seigniorage.
2. Added note clarifying reward distribution ratio calculation for easy reference. 
----
=> Update notes on Reward.go

.github/ISSUE_TEMPLATE/terra_improvement_proposal__tip_.md
Add TIP issue template
- https://github.com/evanorti/tips
----
=> add tip issue template

x/market/module_test.go, x/oracle/module_test.go, x/wasm/keeper/msg_server_test.go, x/wasm/keeper/querier_test.go, x/wasm/module_test.go, x/wasm/types/connector_test.go, x/wasm/types/contract_test.go, x/wasm/types/gas_meter_test.go, x/wasm/types/genesis_test.go, x/wasm/types/msg_binding_test.go, x/wasm/types/msgs_test.go, x/wasm/types/params_test.go
Add testcase for code coverage
----
=> [Chore] coverage

x/oracle/keeper/slash.go, x/oracle/keeper/slash_test.go, x/oracle/types/events.go
Replace #702 
Append oracle slash events when the validator got slashed due to oracle miss for tracking.
----
=> [Feature] Add oracle slashing event

x/oracle/abci.go, x/oracle/abci_test.go
=> [Feature] no rewards for the validators who missed any oracle votes

app/app.go, app/app_test.go, app/const.go, app/sim_test.go, go.mod
add app creation and export test
----
=> Add app test

go.mod, go.sum
- Update the replace directive of the `cosmos-sdk` fork to commit [515df8b16c89](https://github.com/terra-money/cosmos-sdk/tree/515df8b16c89887b32842200a9271ed7fa28bb82) which contains the following PR: https://github.com/terra-money/cosmos-sdk/pull/63
----
=> chore: update Terra Cosmos SDK dep

CHANGELOG.md, custom/bank/simulation/operations.go, go.mod, go.sum, x/market/simulation/operations.go, x/oracle/simulation/operations.go, x/wasm/simulation/operations.go
This PR merges [terra-rebels:release/v0.44.x-final](https://github.com/terra-rebels/cosmos-sdk/tree/release/v0.44.x-final) which includes,
* https://github.com/terra-money/cosmos-sdk/pull/104
----
=> Merge rebels cosmos sdk
