README.md
When i click "The terra protocol" link, `NET::ERR_CERT_COMMON_NAME_INVALID` error occurred.
Since your common name in ssl cert is `terra.money`, you have to remove `www` from the link.
=> Invalid ssl common name

.circleci/config.yml
A try to fix a bug where ci was broken.
Not sure, but it seems like to happen when the name of the repository in Makefile is different from the name of the local source directory: `fatal: No names found, cannot describe anything.`
It would be nice if anyone could merge this pr ASAP.
=> Rename 'terra' to 'core' in src path

Dockerfile
Currently circleci breaks with
`make: *** No rule to make target 'get_vendor_deps'.  Stop.` 
Removing get_vendor_deps reference from Dockerfile to solve this issue.
=> remove get_vendor_deps reference from Dockerfile

Makefile, cmd/init/testnet.go
Now, we don't need to use a customized "testnet" command to support remote-net anymore.
"testnet" command is reverted to the original rule which is supporting local-net only.
=> recovering testnet.go

.circleci/config.yml, .goreleaser.yml, Makefile, version/command.go, version/version.go
Fixed the `version` command in `terrad` cli:
```
$ terrad version --long
core: 0.0.7
git commit: 5f4f08d2ea4de66f9d52a166249678cc1ecc9990
go.sum hash: 2bbcf2782c3fd73c1a2997b2c825b4c3a40646979153ab4ae639dfb027083ab5
build tags: netgo ledger
go version go1.12 darwin/amd64
```
The new version can be defined after tagging (e.g. `git tag v0.x.x`) and will be released with CI.
=> Fix version info

x/oracle/client/cli/tx.go
in terracli, the voting price was converted to int64 type.
It needs to support sdk.Dec type.
=> bugfix: float type voting price support

docs/concepts/validator/validator-faq.md, docs/guide/deploy-testnet.md, docs/guide/join-network.md
Changed representation of block rewards as being payable in luna to SDT (TerraSDR)
=> fix validator faq

cmd/init/testnet.go, docs/guide/deploy-testnet.md, docs/guide/terracli.md, docs/guide/validators.md, types/assets/assets.go, x/market/client/cli/tx.go, x/oracle/client/cli/query.go, x/oracle/client/cli/tx.go, x/treasury/client/cli/query.go
Currently, on-chain assets were defined as "musd" "mluna" for 10^-6 th of the parent asset. For micro units, the convention is to prefix 'u' instead of 'm'
https://en.wikipedia.org/wiki/International_System_of_Units#Prefixes
Changed all asset prefixes to 'u' instead of 'm'.
=> Changing micro currency units from m-asset to u-asset

app/genesis.go, cmd/init/testnet.go, docs/guide/deploy-testnet.md, docs/guide/terracli.md, docs/guide/validators.md, go.sum, types/assets/assets.go, types/graded_account.go, types/graded_account_test.go, x/market/client/cli/tx.go, x/oracle/client/cli/query.go, x/oracle/client/cli/tx.go, x/treasury/client/cli/query.go
Terra genesis accounts have a unique vesting schedule that doesn't play nicely with continuousVestingAccount + DelayedVestingAccount implementation of the cosmos sdk. Doing our own! GradedVestingAccount allows the user to specify a "VestingSchedule", which maps the percentage of OriginalVesting tokens to become liquid to unix blocktimes. 
Must accomodate: 
- pre-seed investors (10%, 10%, 10%, 70%) 
- seed investors (10%, 10%, 10%, 70%) 
- private investors (10%, 10%, 10%, 10%, 10%) for Luna,  1/12 per year for TerraSDR
- employee vesting (3-4 years) 
- Implemented a GradedVestingAccount that follows the above specs
- Changed genesis.json to play nicely with GradedVestingAccount
=> Implemented graded vesting accounts for Terra genesis

x/bench/oracle_bench_test.go, x/oracle/ballot_test.go, x/oracle/client/cli/query.go, x/oracle/client/cli/tx.go, x/oracle/client/module_client.go, x/oracle/client/rest/query.go, x/oracle/client/rest/tx.go, x/oracle/codec.go, x/oracle/end_blocker.go, x/oracle/end_blocker_test.go, x/oracle/errors.go, x/oracle/handler.go, x/oracle/handler_test.go, x/oracle/keeper.go, x/oracle/keeper_keys.go, x/oracle/keeper_test.go, x/oracle/msg.go, x/oracle/msg_test.go, x/oracle/querier.go, x/oracle/querier_test.go, x/oracle/tags/tags.go, x/oracle/test_common.go, x/oracle/vote.go
I implemented delegation of oracle voting rights to other Account addresses.
By using the `MsgDelegateFeederPermission` a validator can assign the right to vote to another account at any time. The validator account will preserve its right to vote at any time.
A single account can have the right to vote on behalf of multiple validators.
A vote message must now contain the validator to vote on behalf of and the sender/feeder address.
=> Implement voting right delegation for oracle

docs/guide/installation.md, docs/guide/join-network.md
1. Dependencies (`golang-statik` and `golangci-lint`) were missing on installation doc
2. `genesis.json` Github URL was outdated
=> Update genesis URL

CHANGELOG.md, README.md, docs/features/overview/README.md, docs/features/overview/validator-faq.md, docs/features/stability.md, docs/guide/installation.md, docs/guide/join-network.md, docs/guide/terracli.md, docs/guide/users.md, docs/spec/oracle.md, x/market/client/cli/query.go, x/market/client/cli/tx.go, x/market/client/module_client.go, x/oracle/client/cli/query.go, x/oracle/client/cli/tx.go, x/pay/client/cli/sendtx.go, x/treasury/client/cli/query.go
- changed validator-faq to be more consistent with reality
- improved oracle specs to include more specific instruction 
- improved cli comments for readability and grammar
- updated network status for `columbus-2` 
- Added changelog for v0.2.1
=> Documentation update for columbus-2

go.mod, go.sum
update cosmos-sdk version to support ledger hrp customization. 
$terracli keys show {key_name} -d will show terra address
** Report of required housekeeping ** 
======
** (FOR ADMIN) Before merging **
=> update cosmos-sdk version to support ledger hrp customization

docs/guide/terracli.md
Missing `tx` command in some examples.
Might be related to changes made in https://github.com/terra-project/core/commit/bf300d65eb869bdc918be477ca75650769386058
======
** (FOR ADMIN) Before merging **
=> Documentation: add missing `tx`s in terracli documentation

CHANGELOG.md, app/app.go, app/genesis.go, client/lcd/swagger-ui/swagger.yaml, types/codec.go, types/lazy_graded_account.go, types/lazy_graded_account_test.go, update/end_blocker.go, update/plan/test_common.go, update/plan/update_230000.go, update/plan/update_230000_test.go
Apply lazy vesting schedule to all account at 230000 height 
(Estimated: Sun Jun 23 2019 00:50:00 GMT+0000 (UTC))
OracleRewardBand: 1% => 2%
DailyLunaDeltaCap: 0.5% => 0.1%
Solve #180, #181 
** Report of required housekeeping ** 
======
** (FOR ADMIN) Before merging **
=> Feature/ Lazy Vesting Schedule

Makefile, client/keys/add_ledger_test.go, go.mod, go.sum
**Summary of changes** 
Previous cosmos-sdk version has mock ledger which does not support custom coinType. This PR updates cosmos-sdk's mock ledger to support custom coinType. 
**Report of required housekeeping** 
======
**(FOR ADMIN) Before merging**
=> Change cosmos-sdk's mock ledger to accept custom coin type from config

.github/pull_request_template.md, CHANGELOG.md
=> Updated CHANGELOG

docs/features/overview/validator-faq.md, docs/guide/deploy-testnet.md, docs/guide/installation.md, docs/guide/join-network.md, docs/guide/terracli.md, docs/guide/users.md, docs/guide/validators.md, docs/specifications/oracle.md
Use [Hints and Callouts](https://docs.gitbook.com/content-editing/rich-content#hints-and-callouts) instead of `::: <level> <message> :::` notation.
Gitbook documentation is not well made about those tags but [here](https://gitbook.canny.io/feature-requests/p/hints-callouts)'s some discussion on it.
PS: Not sure if there's a way to preview it, to be sure it doesn't actually break something, especially when there is code markup in the hint.
----
=> Update docs hints with tags

client/lcd/swagger-ui/swagger.yaml
=> Correct minor typo in swagger

.circleci/config.yml, .goreleaser.yml
- Bump go version in the circleci `release` step to the same version used by the tests.
- Replace [deprecated](https://goreleaser.com/deprecations/#archive) `archive` directive.
Related to #206 
----
=> Feature/ Minor goreleaser changes

README.md
Add permanent unlimited use invite link to Terra discord channel.
Close #210
=> fix discord link in readme

client/lcd/swagger-ui/swagger.yaml
`uluna` will never figure in the response as it's the market oracle votes are based on.
=> Fix `oracle/denoms/actives` example in swagger

docs/SUMMARY.md, docs/features/overview/validator-faq.md, docs/guide/README.md, docs/guide/deploy-testnet.md, docs/guide/installation.md, docs/guide/join-network.md, docs/guide/ledger-nano-support.md, docs/guide/light-client.md, docs/guide/production.md, docs/guide/terracli.md, docs/guide/users.md, docs/guide/validators.md, docs/specifications/market.md, docs/specifications/oracle.md
guide document update for columbus-3
----
=> Update guide document for columbus-3

x/auth/internal/types/codec.go
When we query module account to auth endpoint, it returns following error
```
terracli query account terra1jgp27m8fykex4e4jtt0l7ze8q528ux2lh4zh0f --trust-node
ERROR: unrecognized concrete type name supply/ModuleAccount
```
So we need to register supply/ModuleAccount to auth ModuleCdc for query end point.
----
=> [Bugfix] Register supply/ModuleAccount to auth ModuleCdc

x/oracle/internal/types/msgs.go
* Fix oracle invalid prevote hash error msg to print byte length not string length
----
=> [Bugfix] Fix oracle invalid prevote hash error msg

x/oracle/internal/types/params.go
We shortened the default oracle `VotePeriod` to 30 seconds. Action to @YunSuk-Yeo to reflect this change in the genfile (#244) in the next release  
----
=> shortened default oracle voteperiod to 30 seconds. 

x/treasury/abci.go, x/treasury/genesis.go, x/treasury/handler.go, x/treasury/internal/keeper/indicator.go, x/treasury/internal/keeper/keeper.go, x/treasury/internal/keeper/params.go, x/treasury/internal/keeper/policy.go, x/treasury/internal/keeper/querier.go, x/treasury/internal/keeper/seigniorage.go, x/treasury/internal/types/events.go
* minor treasury comments update
----
=> [Feature] minor treasury comments update

x/treasury/internal/keeper/indicator_test.go, x/treasury/internal/keeper/policy_test.go
=> [Bugfix] Fix merge err

x/market/alias.go, x/market/internal/types/params.go, x/oracle/internal/types/params.go, x/treasury/genesis.go, x/treasury/genesis_test.go
* Change treasury init genesis to use current supply when epoch initial issuance is empty
* Update default params of oracle and market module
- `BasePool` of oracle: 250,000 SDT
- `SlashWindow` of market: window for a day
----
=> [Feature] Update treasury init genesis & oracle,market default params

.circleci/config.yml
Related to job failure:
https://app.circleci.com/jobs/github/terra-project/core/3048
Should allow circleci to checkout tags
Please if you see a consequent increase in build time @YunSuk-Yeo tell me
=> Remove git caching in circleci jobs

x/oracle/client/rest/query.go
* `/oracle/voter/{%s}/prevotes` => `/oracle/voters/{%s}/prevotes`
* `/oracle/voter/{%s}/votes` => `/oracle/voters/{%s}/votes`
----
=> [Bugfix] Fix oracle rest path

.gitignore, x/oracle/client/rest/query.go, x/oracle/internal/types/genesis.go
* Fix to bind height to rest response
* Fix to parse height query for some oracle endpoints
----
=> [Bugfix] Bind height to rest query response

client/lcd/swagger-ui/swagger.yaml, x/market/internal/types/params.go, x/oracle/abci.go, x/oracle/abci_test.go
* skip oracle slashing for the not passed ballot
close #278 
----
=> [Bug] Skip oracle slashing for the not passed ballot

Makefile, contrib/devtools/Makefile, contrib/devtools/install-golangci-lint.sh
* Add swagger sync feature
close #282 
----
=> [Bugfix] Add features to sync swagger doc

x/oracle/abci_test.go, x/oracle/internal/keeper/reward.go, x/oracle/internal/keeper/reward_test.go, x/oracle/internal/types/params.go, x/oracle/internal/types/params_test.go, x/oracle/slash_test.go, x/oracle/slashing.go, x/oracle/test_utils.go
* Align oracle params (`RewardDistributionWindow`, `SlashingWindow`) to units of blocks
close #277 
----
=> [Bug] Align oracle parameters to units of blocks

x/market/internal/types/params.go, x/oracle/internal/types/params.go, x/treasury/internal/types/constraint.go, x/treasury/internal/types/params.go
* Align each modules params stringify
close #285 
----
=> [Bugfix] Align params stringify

CHANGELOG.md
clog update for next release
----
=> clog update

x/market/alias.go, x/market/internal/keeper/querier.go, x/market/internal/keeper/querier_test.go, x/market/internal/keeper/swap.go, x/market/internal/types/errors.go, x/market/internal/types/msgs.go, x/market/internal/types/msgs_test.go, x/oracle/internal/types/errors.go, x/oracle/internal/types/msgs.go, x/oracle/internal/types/msgs_test.go
* prevent overflow by blocking huge input at msg validation & querier
----
=> [Bugfix] oracle & market overflow 

x/market/internal/types/params.go, x/oracle/genesis.go, x/oracle/internal/keeper/keeper.go, x/oracle/internal/keeper/keeper_test.go, x/oracle/internal/keeper/reward.go
* Crate oracle account at init genesis to prevent the the bank module make the oracle account address (`terra1jgp27m8fykex4e4jtt0l7ze8q528ux2lh4zh0f`) as general account.
close #292  
----
=> [Bugfix] Create oracle account at init genesis

types/alias.go, types/assets/assets.go, x/market/alias.go, x/market/internal/keeper/params.go, x/market/internal/keeper/swap.go, x/market/internal/keeper/swap_test.go, x/market/internal/types/genesis_test.go, x/market/internal/types/params.go, x/market/internal/types/tobin_tax.go, x/oracle/internal/types/denom.go, x/oracle/internal/types/vote.go
* Add market parameter `TobinTaxList` to specify a more strict tobin tax for the denoms with high volatility
* Apply highest `TobinTax` between [default=`TobinTax`, `TobinTaxList['Denom'=offerDenom]`, `TobinTaxList['Denom'=askDenom]`]
----
=> [Feature] New market params for the high volatility TERRA

client/lcd/swagger-ui/swagger.yaml
* Fix sdk part of swagger 
----
=> [Docs] Update swagger

contrib/updates/columbus-2-to-columbus-3.py
* Delete unused budget from the genesis
* Add if statement for the safe unbonding balance check
* Change illiquid_tobin_tax_list to list
* Decrease oracle slashing fraction to 0.01%
----
=> [Bugfix] genesis script

contrib/devtools/Makefile, contrib/devtools/install-golangci-lint.sh
* Update golangci-lint version
----
=> Update golangci-lint version to v1.22.2

CHANGELOG.md, README.md, client/lcd/swagger-ui/swagger.yaml
* Update change log
* Fix README
----
=> [Docs] Update change log & Fix README

CHANGELOG.md, README.md, client/lcd/swagger-ui/swagger.yaml
* Bump sdk version to v0.37.6
----
=> Bump sdk version to v0.37.6

go.mod, go.sum, x/treasury/abci.go, x/treasury/handler.go, x/treasury/internal/test_common.go, x/treasury/internal/types/events.go
* Update SDK version to [v0.37.7](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.37.7)
* Append treasury proposal events
----
=> [Feature] proposal events

contrib/devtools/Makefile, contrib/devtools/install-golangci-lint.sh
=> [Bugfix] Remove golangci-lint hash verification

app/app_test.go, app/export.go, types/alias.go, types/util/blocks.go, x/treasury/abci.go, x/treasury/abci_test.go, x/treasury/alias.go, x/treasury/genesis.go, x/treasury/genesis_test.go, x/treasury/internal/keeper/indicator.go, x/treasury/internal/keeper/indicator_test.go, x/treasury/internal/keeper/keeper.go, x/treasury/internal/keeper/keeper_test.go, x/treasury/internal/keeper/policy_test.go, x/treasury/internal/keeper/querier.go, x/treasury/internal/keeper/querier_test.go, x/treasury/internal/keeper/seigniorage_test.go, x/treasury/internal/types/genesis.go, x/treasury/internal/types/genesis_test.go, x/treasury/internal/types/keys.go
Now we introduce `CumulatedHeight` to keep indicator histories which are stored per each epoch even if the block height is reset (at hard fork). 
When we export genesis for zero height, it will update `CumulatedHeight` to `CumulatedHeight` + `ctx.BlockHeight()` for next chain without deleting indicator histories.
close #317 
----
=> [Feature] Prevent state reset of treasury after hard fork

x/market/handler.go, x/market/handler_test.go, x/market/test_utils.go
Current market handler crash when it meets zero tobin tax denom(not possible, under columbus-3). This release will prevent crash for the swap between zero tobin tax denoms.
----
=> [Bugfix] Fix market swap handler to properly treat zero spread case

x/oracle/abci.go, x/oracle/abci_test.go
Oracle EndBlocker does not update tobin taxes when there are only tobin tax updates without any denom list changes.
* Fix oracle end blocker to apply tobin tax only changes in whitelist
----
=> [Bugfix] Fix tobin tax upate of oracle end blocker

CHANGELOG.md, go.mod, go.sum
* Bump sdk version to [v0.37.9](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.37.9)
----
=> [Upgrade] Patch Tendermint security update

x/oracle/abci.go, x/oracle/internal/keeper/keeper.go, x/oracle/internal/keeper/keeper_test.go, x/oracle/slash_test.go, x/oracle/slashing.go
* Check bonded & jailed status before oracle slashing
close #341 
----
=> [Bugfix] Oracle Slashing

cmd/terracli/main.go
* Receive `--old-hd-path` flag
* Delay config seal time to viper pre-run step to apply `--old-hd-path` flag
close #356 
----
=> [Feature] support old-hd-path flag

x/wasm/internal/types/codec.go, x/wasm/internal/types/msg.go
* Change WASM related msg codec names  to Msg* for consistency
----
=> [Bugfix] WASM module codec naming

client/lcd/swagger-ui/swagger.yaml
In swagger definition, `TallyResult` response properties has `yes` and `no` as map keys. These are treated respectively `true` and `false` in yaml spec (🤷‍♂️) . This makes spec compliant go yaml parser scream, as in golang maps cannot have `bool` type as keys.
----
=> fix: stringify yes and no map keys

x/auth/simulation/genesis.go, x/auth/vesting/types/vesting_account.go, x/auth/vesting/types/vesting_account_test.go
follow: https://github.com/cosmos/cosmos-sdk/pull/6842, https://github.com/cosmos/cosmos-sdk/pull/6861
Lets merge this with SDK v0.39.1
----
=> [Bugfix] Convert Custom JSON Marshaling Codec to Amino Codec

go.mod, go.sum
* https://github.com/cosmos/cosmos-sdk/releases/tag/v0.39.1
- Change vesting account's custom JSON marshaler to amino codec
- REST server --unsafe-cors mode option
----
=> [Feature] Bump SDK to v0.39.1

go.mod, go.sum
* use custom go-cosmwasm to propagate interrupt signal
ref: https://github.com/CosmWasm/cosmwasm/issues/495
close #363 
----
=> [Feature] Use custom go-cosmwasm for signal propagation

x/oracle/abci.go, x/oracle/abci_test.go, x/oracle/internal/keeper/keeper.go, x/oracle/internal/keeper/test_utils.go, x/oracle/tally.go, x/oracle/test_utils.go
Follow-up of https://github.com/terra-project/core/pull/345#issuecomment-645142148, https://github.com/terra-project/core/pull/345#issuecomment-666961850
1. Add reference Terra
- Let `Vote_j = Vote_j_1 ... Vote_j_n` be the `uluna` exchange rate votes for each terra for validator `Val_j` in a given `VotePeriod`. `n` = number of total terra whitelist
- For all terra whitelist  `w_1 ... w_n`, choose the index `r` with the highest voter turnout. If the vote turnout has multiple tie winner, we choose in alphabetical order. `w_r` is chosen as the reference terra from which to compute cross exchange rates.
2. Fix Oracle Exchange Rate logic
- Each validator now calculate cross exchange rates(`CER`) for `w_i` as below.
- for `i≠r`, `CER_j_i = Vote_j_r / Vote_j_i`
- for `i=r`, `CER_j_i = Vote_j_r` …
=> [Oracle] Exchange Rate and Ballot Rewards logic using reference terra

cmd/terrad/main.go, x/wasm/config/config.go, x/wasm/internal/keeper/keeper.go
* Allow to change WASM store path by changing `db_dir = "data"` in `config.toml`
close #394 
----
=> [Feature] WASM store path customization

x/wasm/internal/keeper/contract.go, x/wasm/internal/keeper/contract_test.go
Fix to store instantiated contract first before executing response messages, then response messages can utilize instantiated contract.
----
=> [Bugfix] Wasm instantiate process

app/app.go, x/gov/internal/types/codec.go, x/msgauth/client/cli/query.go
=> [Feature] Allow gov msg to be grantable

x/oracle/internal/types/msgs.go
This PR maps to the InvalidCoinsError and makes for an easier time debugging AggregateVoteMessages
----
=> Remove CodeSpace undefined error for Mempool errors for ParseExchangeRateTuples 

client/lcd/root.go, go.mod, go.sum
* added a flag to the rest server that if you are fine with accepting all cors you can.
close #409 
----
=> [Feature] add a flag to the rest server to accept all cors

x/auth/vesting/types/schedule.go
Minor decimal precision correction in vesting schedule validation.
close #418 
----
=> [Bugfix] allow language specific decimal precision error in vesting schedule validation

Dockerfile, go.mod, go.sum
The problem is described here https://github.com/CosmWasm/cosmwasm/issues/603.
* Cherry-pick CosmWasm file & memory cache following updates
https://github.com/CosmWasm/cosmwasm/pull/614
https://github.com/CosmWasm/cosmwasm/pull/607
https://github.com/CosmWasm/cosmwasm/pull/606
https://github.com/CosmWasm/cosmwasm/pull/605
https://github.com/CosmWasm/cosmwasm/pull/578
----
=> [Feature] CosmWasm cache update

app/app.go
* Register wasm queriers after initializing staking keeper
close #428 
----
=> [Bugfix] Register wasm queriers after staking keeper initialization

x/wasm/internal/keeper/querier.go, x/wasm/internal/keeper/recursive_test.go
External contract query, which is causing out-of-gas, also causes core node panic. 
In this PR, I added recover statement to prevent panic from the out-of-gas error.
close #431 
----
=> [Bugfix] Prevent panic when external contract query executed

client/lcd/swagger-ui/swagger.yaml, x/auth/client/rest/query.go
* Remove custom `tx.height` interpretation
* Update swagger to apply new flags `tx.minheight` & `tx.maxheight`
* Enforce to use` tx.height` or (`tx.maxheight` & `tx.minheight`) events when rest-server is running with `--public` flag
----
=> [Feature] append blocking conditions for `/txs` query with `--public` flag on LCD

go.mod, go.sum
Bump go-cosmwasm version to fix memory leak in contract store iterator
----
=> [Hotfix] memory leak in go-cosmwasm iterator

x/treasury/abci_test.go, x/treasury/internal/keeper/keeper.go, x/treasury/internal/keeper/keeper_test.go
fix: #444 
The protection code for `division by zero`, due to empty epoch data, is added.
----
=> [Hotfix] treasury empty epoch data

.circleci/config.yml
publish docker images to docker hub on `publish/*`branches.
Useful for deploying test versions
branch `publish/test-something` → `terramoney/core:test-something`
=> Add delivery on `publish/*` branches

cmd/terrad/main.go, x/auth/ante/ante.go, x/auth/ante/spamming_prevention.go, x/auth/ante/tax.go
To prevent spamming attack,
We added new flag `tx-gas-hard-limit` to terrad cmd.
Default tx-gas-hard-limit is 30,000,000.
and node operators can set in any other value.
> This change is only applied to mempool operation (check tx), so can be applied anytime without consensus failure
```
$ terrad start --tx-gas-hard-limit 10,000,000
```
----
=> [Feature] add tx-gas-hard-limit flag to prevent spamming attack

app/app.go, types/util/softfork.go, x/auth/ante/spamming_prevention.go, x/auth/ante/spamming_prevention_test.go
* The ante handler will block the tx with high gas than 30,000,000
* Update ConsensusParams MaxGas = 30,000,000
```
// Expected time:
// MAINNET
// Tue Mar 30 2021 18:00:00 GMT+0900 (KST)
// Tue Mar 30 2021 09:00:00 GMT+0000 (UTC)
// Tue Mar 30 2021 01:00:00 GMT-0800 (PST)
//
// TEQUILA
// Tue Mar 25 2021 18:00:00 GMT+0900 (KST)
// Tue Mar 25 2021 09:00:00 GMT+0000 (UTC)
// Tue Mar 25 2021 01:00:00 GMT-0800 (PST)
```
----
=> [Hotfix] prevent huge gas tx

app/legacy/migrate.go, app/legacy/v05/migrate.go, custom/auth/legacy/v040/migrate.go, x/wasm/keeper/recursive_test.go, x/wasm/legacy/v05/migrate.go, x/wasm/legacy/v05/migrate_test.go, x/wasm/types/params.go
* update consensus_params
```
// increase block consensus params
genDoc.ConsensusParams.Block.MaxBytes = int64(3000000)
genDoc.ConsensusParams.Block.MaxGas = int64(100000000)
// decrease evidence max bytes
genDoc.ConsensusParams.Evidence.MaxBytes = int64(50000)
```
* update wasm params
```
// decrease contras max gas
MaxContractGas:      20_000_000,
// increase contract data size
MaxContractDataSize: 1024,
```
----
=> Update migration params for col5

x/oracle/wasm/interface.go, x/oracle/wasm/interface_test.go, x/wasm/keeper/connector.go, x/wasm/keeper/custom_test.go, x/wasm/types/msg_binding.go
=> [Bugfix] Return BASE/QUOTE exchange rate

x/wasm/keeper/api.go, x/wasm/keeper/connector.go, x/wasm/keeper/contract.go, x/wasm/keeper/msg_server.go, x/wasm/keeper/msg_server_test.go, x/wasm/keeper/recursive_test.go, x/wasm/keeper/submsg_test.go, x/wasm/types/errors.go
=> [Bugfix] limit wasm max gas with param

client/lcd/root.go
Support preflight requests triggered by the Content-Type header to the rest server when `--unsafe-cors` flag is used.
When making a request to the rest server from a web browser, if the request includes a Content-Type other than those listed [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests), it will trigger a preflight request.
That request currently fails with a `403` status code.
After this change, it will return `200`.
Right now, if a user is running localterra on their development machine and uses terra.js to make a POST request (e.g. `/txs/estimate_fee` via [estimateFee](https://github.com/terra-money/terra.js/blob/7bbff355d74e40ff9e558ab7791b5c1c6dfa4640/src/client/lcd/api/TxAPI.ts#L270)), that request will trigger a preflight request and fail. It will …
=> Support Content-Type preflight requests to rest server when using --unsafe-cors flag

x/oracle/tally.go, x/oracle/types/ballot.go
Apply final audit recommend.
* Remove unused sorted check
----
=> remove unused sorted check

x/wasm/types/connector.go, x/wasm/types/connector_test.go
close #528
We try dereferencing the event, so before building the event we have to check the length.
----
=> [Bugfix] fix panic at wasm event parse

CHANGELOG.md, x/oracle/legacy/v05/migrate.go, x/treasury/legacy/v05/migrate.go
=> [Bugfix] sort migrated map array to get deterministic result

CHANGELOG.md, app/app.go, custom/auth/legacy/v039/types.go, custom/auth/legacy/v040/migrate.go, custom/auth/legacy/v040/migrate_test.go, custom/auth/legacy/v040/store.go
fix #562 
Use custom LegacyAminoPubkey for multisig account pub key.
To softly upgrade bombay-11 network, we add upgrade handler for pain name `multisig-pubkey-migration`.
----
=> fix to use amino multisig pubkey at migration

client/docs/swagger-ui/swagger.yaml, client/docs/swagger_legacy.yaml, custom/auth/client/rest/broadcast.go, custom/auth/client/rest/encode.go, custom/auth/client/rest/rest.go, x/wasm/keeper/connector.go
=> [Bugfix] emit missing wasm tax events

client/docs/swagger-ui/swagger.yaml, client/docs/swagger_legacy.yaml, custom/auth/client/rest/broadcast.go, custom/auth/client/rest/encode.go, custom/auth/client/rest/rest.go
implement `/txs/encode` endpoint for Backward compatibility to convert a legacy StdTx into new Proto style txbytes.
----
=> [Feature] legacy tx encode support

x/wasm/keeper/keeper.go
=> [bugfix] change `write-vm-memory-cache-size` default config replace location

x/wasm/keeper/contract.go, x/wasm/keeper/keeper.go, x/wasm/keeper/recursive_test.go, x/wasm/types/errors.go, x/wasm/types/wasmer_engine.go
Reject tx which is executing  deep recursive query to prevent node crash.
* Set max query depth to `20`
----
=> [Hotfix] block deep recursive query

app/app.go, custom/auth/ante/ante.go
Append IBC ante decorator to reject transactions that only contain redundant packet messages. This will prevent relayers from wasting fees by submitting messages for packets that have already been processed by previous relayer(s). The Antedecorator is only applied on CheckTx and RecheckTx and is therefore optional for each node. 
----
=> [Feature] add ibc ante to prevent duplicate packet from relayer

Dockerfile, go.mod, go.sum, shared.Dockerfile
close #585 
We found when we use other allocator like tcmalloc or jemalloc, the memory usage is claim than normal malloc function.
In order to replace rust global allocator, we forked [CosmWasm/wasmvm](https://github.com/CosmWasm/wasmvm) and made jemalloc as global allocator.
forked repo can be found [here](https://github.com/terra-money/wasmvm)
----
=> [Feature] use jemalloc as wasm global memory allocator

CHANGELOG.md, x/wasm/keeper/contract.go, x/wasm/keeper/keeper.go, x/wasm/keeper/legacy_querier.go, x/wasm/keeper/pool.go, x/wasm/keeper/querier.go, x/wasm/keeper/recursive_test.go, x/wasm/types/keys.go
close #587 
Also previously, only single wasmvm was used because wasm keeper did not maintain reference of ReadVMPool.
----
=> [Bugfix] fix to use single wasmvm during recursive external query

CHANGELOG.md, Dockerfile, go.mod, go.sum, shared.Dockerfile
Reverts terra-money/core#586
close #592 
Instead adopting jemalloc only for wasmvm, we need to replace whole memory allocator of terrad process.
for that,
1. Install `jemalloc`.
```bash
JEMALLOC_VERSION=5.2.1
wget https://github.com/jemalloc/jemalloc/releases/download/$JEMALLOC_VERSION/jemalloc-$JEMALLOC_VERSION.tar.bz2 
tar -xf ./jemalloc-$JEMALLOC_VERSION.tar.bz2 
cd jemalloc-$JEMALLOC_VERSION
./configure --with-malloc-conf=background_thread:true,metadata_thp:auto,dirty_decay_ms:30000,muzzy_decay_ms:30000
make
sudo make install
```
2. Restart the process with `LD_PRELOAD=/usr/local/lib/libjemalloc.so terrad start`.
If you are using `systemd` or another process manager to launch `terrad`, you might need to configure them. The following  sample `systemd` file fixes the problem:
```systemd …
```
=> Revert "[Feature] use jemalloc as wasm global memory allocator"

CHANGELOG.md, go.mod, go.sum
close #599 
This update is security update of wasmvm [ref](https://gist.github.com/webmaster128/99f48b6e1de51453935a6f32da4ad3ee).
The problem monitored only happens in the nodes which are receiving wasm queries, so the query nodes are highly recommended to update ASAP to avoid node crash.
----
=> [Bugfix] Bump wasmvm to v0.16.2

docker/Dockerfile, docker/README.md, docker/build_all.sh, docker/entrypoint.sh
The first version of this node attempted to change the `db_dir` value in the config.toml, which ended up not actually working as expected. Instead I've refactored this to use the `--db_dir` flag to specific a different directory and this is working much better. 
I also added to the docs a bit, 
----
=> Update Docker images to use the `--db_dir` flag. 

x/wasm/genesis.go
=> [Bugfix] skip get byte when exporting not migrated code

app/export.go
=> [Bugfix] export for zero height 

docker/entrypoint.sh
* Add `sfo` to default quicksync.io URL to use San Francisco as default download region. This is need because `get.quicksync.io` no longer hosts any snapshots. Unless users explicitly sets the `SNAPSHOT_BASE_URL`, snapshots won't work.
* Check for existing of .db files in the `$DATADIR`. Some implementations of k8s filesystem drivers automatically add `.Trash` or `lost+found` directories. The `[[ ! -z ]]` operator will catch these and skip the snapshot. Using `find` to check for explicit `.db` files will tell us if Cosmos has stored any state here yet.
- Tested first change by setting `SNAPSHOT_BASE_URL` to `https://getsfo.quicksync.io` explicitly.
- Tested second change by running the entrypoint with a variety of files/dirs on the filesystem, ensuring snapshot did not start if any .db …
=> Fix snapshot

Makefile, README.md, cmd/terrad/root.go
close #653 
* fix makefile to pass RocksDB build option
* create snapshot folder for initializing rocksdb. rocksdb does not create parent folder automatically
* add cmd example for rocksdb build option
----
=> [BugFix] makefile to properly pass RocksDB build options

go.mod, go.sum
We monitored #599 error when we use concurrent ABCI wasm query. 
so to pervent this problem on main branch, we updated forked cosmos-sdk and tendermint to use Mutex instead of RWMutex on ABCI query. 
Even we revert RWMutex updates, this branch still contains rocksdb updates #654  and configurable IAVL and inter-block cache updates #655 .
so node operators can configure these values in ~/.terra/config/app.toml
```toml
inter-block-cache-size = 78125
iavl-cache-size = 781250
```
or can use rocksdb by building terrad with
```bash
COSMOS_BUILD_OPTIONS=rocksdb make install
```
----
=> update tendermint to use Mutex instead RWMutex for query safety

Makefile, README.md, cmd/terrad/root.go, go.mod, go.sum
Update performance branch to use performance branch of `cosmos-sdk` and `tendermint`
It also add rocksdb #654  and configurable IAVL and inter-block cache update #655.
This branch is supposed to use `RWMutex` on ABCI query.
in ~/.terra/config/app.toml
```toml
inter-block-cache-size = 78125
iavl-cache-size = 781250
```
or can use rocksdb by building terrad with
```bash
COSMOS_BUILD_OPTIONS=rocksdb make install
```
----
=> RWMutex tendermint

Makefile
Applying suggested flag update
```
Failure: flag --against-input is no longer supported, use --against instead
```
Please see [build output](https://github.com/terra-money/core/runs/4772562041?check_suite_focus=true)
----
=> use --against instead

Makefile, client/docs/swagger-ui/swagger.yaml, docs/core/proto-docs.md, third_party/proto/cosmos/auth/v1beta1/query.proto, third_party/proto/cosmos/authz/v1beta1/authz.proto, third_party/proto/cosmos/authz/v1beta1/event.proto, third_party/proto/cosmos/authz/v1beta1/genesis.proto, third_party/proto/cosmos/authz/v1beta1/query.proto, third_party/proto/cosmos/authz/v1beta1/tx.proto, third_party/proto/cosmos/bank/v1beta1/authz.proto, third_party/proto/cosmos/bank/v1beta1/bank.proto, third_party/proto/cosmos/bank/v1beta1/query.proto, third_party/proto/cosmos/base/abci/v1beta1/abci.proto, third_party/proto/cosmos/base/query/v1beta1/pagination.proto, third_party/proto/cosmos/base/reflection/v2alpha1/reflection.proto, third_party/proto/cosmos/base/store/v1beta1/listening.proto, third_party/proto/cosmos/base/tendermint/v1beta1/query.proto, third_party/proto/cosmos/crypto/secp256r1/keys.proto, third_party/proto/cosmos/feegrant/v1beta1/feegrant.proto, third_party/proto/cosmos/feegrant/v1beta1/genesis.proto, third_party/proto/cosmos/feegrant/v1beta1/query.proto, third_party/proto/cosmos/feegrant/v1beta1/tx.proto, third_party/proto/cosmos/gov/v1beta1/gov.proto, third_party/proto/cosmos/gov/v1beta1/tx.proto, third_party/proto/cosmos/staking/v1beta1/authz.proto, third_party/proto/cosmos/tx/v1beta1/service.proto, third_party/proto/cosmos/upgrade/v1beta1/query.proto, third_party/proto/cosmos/upgrade/v1beta1/upgrade.proto
Apply cosmos proto changes
Critical Change is 
from `/cosmos/bank/v1beta1/balances/{address}/{denom}`
to `/cosmos/bank/v1beta1/balances/{address}/by_denom?denom={denom}`
----
=> apply cosmos-sdk proto updates 

CHANGELOG.md, x/wasm/keeper/contract.go, x/wasm/keeper/submsg_test.go, x/wasm/types/gas_store.go, x/wasm/types/gas_store_test.go
fix - https://github.com/cosmos/cosmos-sdk/issues/10243
This update makes gas `KVStore` to charge gas cost for the key length to prevent cheap store operation from the contract. 
This also requires softfork.
|               | columbus-5                | bombay-12                 |
| ------------- | ------------------------- | ------------------------- |
| Height        | 6,470,000                 | 7,800,000                 |
| Expected Time | 2022-02-13T15:00:00 (UTC) | 2022-02-11T15:00:00 (UTC) |
----
=> [HotFix] fix to charge gas cost for the key length in wasm execution

Dockerfile
In order to improve a bit the Docker image, i suggest to pin the version used in the builder and in the final Docker image.
Another point is to avoid to run container as root. For this, create a dedicated user and run terrad with it.
**HINT**: this could break previous setup running as root because the data will be owned by root. Users will need to change data permissions.
Signed-off-by: Pierre-Emmanuel Andre <pierre-emmanuel.andre@skillz.io>
* Pin docker image versions
* Create and use a dedicated user to run the final Docker image
----
=> Improve Docker image

app/app.go
=> add channel freeze
